### ISSUE TITLE
can it suppprt for downloading tv series 

### ISSUE THREAD

**Issue by ownerowner** [maxwell-martin/netflix-movies-scraper#2]
if it can download videos with 1080P resolution and more subtitles，thanks for replying

**Comment by maxwell-martin** [comment]
This seems possible. However, it is not something that I am going to attempt to do. While doing this project, I came across multiple scenarios where Netflix locked my account for a certain period of time. Since the account that I am using is my family's, I am not going to jeopardize getting the account banned. In addition, Netflix doesn't want people scraping their site, so I am going to follow their rules.

Nonetheless, thanks for reaching out and checking out the project!
